### PR TITLE
WIP: Add exporting graphs into Gephi-supported formats

### PR DESCRIPTION
**Pull request by lpawelcz**
Write entity relation matrix into csv file to have ability to work with Gephi.

### CODE REVIEW

**Comment by lpawelcz** [comment]
We should force lint to ignore those import errors if we cannot get rid of them @wojtasiq @Isild

**Review by Isild — APPROVED** [review]

**Comment by lpawelcz** [comment]
actually, we changed gephi format to GDF instead of CSV because it enables us to use more than one attribute (edge weight and type for example)

**Comment by lpawelcz** [comment]
Sample graph exported with GDF into Gephi:
gephi_gdf

**Comment by wojtasiq** [comment]
Close or finish?

**Pull request closed without merging**
