### PR TITLE
Linting python in github actions

### PR DESCRIPTION
**Pull request by wojtasiq**
Się pobawiłem i dodałem lintera do pythona - lintuje tylko folder server ;)

### CODE REVIEW

**Comment by wojtasiq** [comment]
I can add this also to script folder? @Isild @lpawelcz

**Comment by lpawelcz** [comment]
> I can add this also to script folder? @Isild @lpawelcz

I guess that it will be ok

**Comment by Isild** [comment]
yes you can!

**Comment by wojtasiq** [comment]
@Isild @lpawelcz https://github.com/Isild/ZIWG/pull/10/files Here you have your errors ;P

**Comment by wojtasiq** [comment]
@Isild @lpawelcz should l merge (and you will fix errors by PR to master) or wait for your to fix errors on this branch?

**Pull request merged**
