### PR TITLE
Saving to json, loading from json, saving svg to png

### PR DESCRIPTION
**Pull request by wojtasiq**
Added ability to save graph changes and load them.
Added saving graph to PNG

### CODE REVIEW

**Comment by wojtasiq** [comment]
Example saved graph
graph-3

**Comment by wojtasiq** [comment]
Whole page
Screenshot_2020-05-24 client

**Comment by Isild** [comment]
Is possibility to save not only view from window view but all generated graph?

**Comment by Isild** [comment]
@wojtasiq

**Comment by wojtasiq** [comment]
> 
> 
> Is possibility to save not only view from window view but all generated graph?

It is saving current view. When you zoom/arrange graph that it is all visible it will export as a whole.

**Pull request merged**
